### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by redlegoman** [plainas/tq#13]
Just installed to Ubuntu 16.04
`Linux mail2 4.5.7-std-3 #1 SMP Tue Jul 12 09:56:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
as per instructions using pip and get this error :

```
$ cat file.html|tq -t title
Traceback (most recent call last):
  File "/usr/local/bin/tq", line 5, in <module>
    tq.main()
  File "/usr/local/lib/python2.7/dist-packages/tq/__init__.py", line 55, in main
    selected_els = get_els(args.selector)
  File "/usr/local/lib/python2.7/dist-packages/tq/__init__.py", line 50, in get_els
    input_stream = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8', errors='ignore')
AttributeError: 'file' object has no attribute 'buffer'
```

**Comment by plainas** [comment]
I should probably improve the documentation a little bit. Reading from with sys.stdin in python 2 is tricky and prone to portability issues like this one. I didn't think that many systems would still default their pip command to python 2. But I think that is still the case of ubuntu.

In your case, to get it to work, uninstall tq with pip uninstall. Then install using **pip3**. Should go something like this:

```
sudo -s
pip uninstall tq
pip3 install https://github.com/plainas/tq/zipball/stable
```

if pip3 is not present install it from ubuntu repositories. The package is called python3-pip

**Comment by plainas** [comment]
I added a mention to this on the readme.

@redlegoman did it work?
