### ISSUE TITLE
Cygwin, Python 2.7.9 compatibility

### ISSUE THREAD

**Issue by flerro** [plainas/tq#8]
Hi, 

thanks for this useful tool, unfortunately it does not seem to be working under cygwin installed on Windows 7. 

Testing on HN I experience the following error.

``` shell
$ curl -s https://news.ycombinator.com/news | tq -tj ".title a"
Traceback (most recent call last):
  File "/usr/bin/tq", line 5, in <module>
    tq.main()
  File "/usr/lib/python2.7/site-packages/tq/__init__.py", line 55, in main
    selected_els = get_els(args.selector)
  File "/usr/lib/python2.7/site-packages/tq/__init__.py", line 51, in get_els
    input_stream = io.TextIOWrapper(sys.stdin.buffer, errors='ignore')
AttributeError: 'file' object has no attribute 'buffer'
(23) Failed writing body
```

Is Python 2.7.9 ok to run your tool?

If you need more info just ask.

**Comment by plainas** [comment]
Hey @flerro 

The instructions might be wrong now that I think about it.

Try uninstalling with:

```
 pip uninstall tq
```

then install using '`pip3` instead of `pip`.

**Comment by plainas** [comment]
On my system `pip install` installed the package to /usr/lib/python3.5. I use Manjaro Linux, not sure about what happens on cygwin, but in your case it looks like it defaults to python2.

**Comment by flerro** [comment]
I will try with pip3 and let you know (not before next wednesday).
Il 05 dic 2015 17:17, "plainas" notifications@github.com ha scritto:

**Comment by flerro** [comment]
Let's mark this as closed as it seems my python installation is quite messed up, installing via `pip3` gives a bunch of errors.

Luckily I'm going to switch back to Linux soon.

Regards.
